spring.application.name=Job_queues

# Redis configuration using Docker service
spring.data.redis.host=${SPRING_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.data.redis.database=0
spring.data.redis.timeout=5000