version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "${SPRING_REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: springboot-app
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SPRING_REDIS_PORT=${SPRING_REDIS_PORT}